@apiUrl = http://localhost:3000/api/v1
@userURL = {{apiUrl}}/auth

@transactionURl = {{apiUrl}}/transactions

POST {{userURL}}/register
Content-Type: application/json

{
    "username":"manish",
    "email": "test123@gmail.com",
    "password": "123456"
}

### login request
POST {{userURL}}/login
Content-Type: application/json

{
    "email" : "test123@gmail.com",
    "password" : "123456"
}


###
POST {{transactionURl}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxMjNAZ21haWwuY29tIiwiaWF0IjoxNzcyMzI3NTA2LCJleHAiOjE3NzIzMjc1NjZ9.mYTLLyOyhtk2FiJtGESRoZqiGdosHieSewRpFhqFC8g
Content-Type: application/json

{
    "type":"expense",
    "amount": "100",
    "tDate":"2026-02-25",
   "description": "fuel"
}
###
GET {{transactionURl}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxMjNAZ21haWwuY29tIiwiaWF0IjoxNzcyMzI3NTA2LCJleHAiOjE3NzIzMjc1NjZ9.mYTLLyOyhtk2FiJtGESRoZqiGdosHieSewRpFhqFC8g

###
PATCH {{transactionURl}}/69a38331763a7f3ae7a7127c
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxMjNAZ21haWwuY29tIiwiaWF0IjoxNzcyMzI2MDQyLCJleHAiOjE3NzI0MTI0NDJ9.0ZcxrYG4rBMZ3Ua0ZNicrNzSps6KMKh6urjgBiZnK9s
Content-Type: application/json

{
    "type":"expense",
    "amount":"100"
}

###
DELETE {{transactionURl}}/69a37ecb5be4a61999a7a228
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxMjNAZ21haWwuY29tIiwiaWF0IjoxNzcyMzI2MDQyLCJleHAiOjE3NzI0MTI0NDJ9.0ZcxrYG4rBMZ3Ua0ZNicrNzSps6KMKh6urjgBiZnK9s

###
DELETE {{transactionURl}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxMjNAZ21haWwuY29tIiwiaWF0IjoxNzcyMzI2MDQyLCJleHAiOjE3NzI0MTI0NDJ9.0ZcxrYG4rBMZ3Ua0ZNicrNzSps6KMKh6urjgBiZnK9s
Content-Type: application/json

{
    "ids": ["69a39134068667756326dc1e","69a3818492a4d161ac55ea21","69a3818492a4d161ac55ea1f"]
}
