@apiUrl = http://localhost:3000/api/v1
@authUrl = {{apiUrl}}/auth
@userUrl = {{apiUrl}}/users

@dashboardUrl = {{apiUrl}}/dashboard

@transactionURl = {{apiUrl}}/transactions

POST {{authUrl}}/register
Content-Type: application/json

{
    "username":"manish",
    "email": "b23@gmail.com",
    "password": "123456"
}

### login request
POST {{authUrl}}/login
Content-Type: application/json

{
    "email" : "b23@gmail.com",
    "password" : "123456"
}


### get user detail
GET {{userUrl}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImIyM0BnbWFpbC5jb20iLCJpYXQiOjE3NzI5MjkxMTMsImV4cCI6MTc3MzAxNTUxM30.Tu27VQ_hKZ1Ld6XOh5RQJJf5jJhP0BWg0bKLFMFSAyo

###
POST {{transactionURl}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImIyM0BnbWFpbC5jb20iLCJpYXQiOjE3NzI5MjkxMTMsImV4cCI6MTc3MzAxNTUxM30.Tu27VQ_hKZ1Ld6XOh5RQJJf5jJhP0BWg0bKLFMFSAyo
Content-Type: application/json

{
    "type":"expense",
    "amount": "100",
    "tDate":"2025-04-25",
    "description": "fuel"
}

###
GET {{transactionURl}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxMjNAZ21haWwuY29tIiwiaWF0IjoxNzcyMzI3NTA2LCJleHAiOjE3NzIzMjc1NjZ9.mYTLLyOyhtk2FiJtGESRoZqiGdosHieSewRpFhqFC8g

###
PATCH {{transactionURl}}/69a38331763a7f3ae7a7127c
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJAZ21haWwuY29tIiwiaWF0IjoxNzcyOTI2OTA3LCJleHAiOjE3NzMwMTMzMDd9.k6E3F_RwVfXs8d9Ax5Z12jEw_BiwH9ghRvDZP3vjnfc
Content-Type: application/json

{
    "type":"expense",
    "amount":"100"
}

###
DELETE {{transactionURl}}/69a37ecb5be4a61999a7a228
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxMjNAZ21haWwuY29tIiwiaWF0IjoxNzcyMzI2MDQyLCJleHAiOjE3NzI0MTI0NDJ9.0ZcxrYG4rBMZ3Ua0ZNicrNzSps6KMKh6urjgBiZnK9s

###
DELETE {{transactionURl}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxMjNAZ21haWwuY29tIiwiaWF0IjoxNzcyMzI2MDQyLCJleHAiOjE3NzI0MTI0NDJ9.0ZcxrYG4rBMZ3Ua0ZNicrNzSps6KMKh6urjgBiZnK9s
Content-Type: application/json

{
    "ids": ["69a39134068667756326dc1e","69a3818492a4d161ac55ea21","69a3818492a4d161ac55ea1f"]
}

###
GET {{dashboardUrl}}
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImIyM0BnbWFpbC5jb20iLCJpYXQiOjE3NzI5MjkxMTMsImV4cCI6MTc3MzAxNTUxM30.Tu27VQ_hKZ1Ld6XOh5RQJJf5jJhP0BWg0bKLFMFSAyo

